class Move {
    constructor(fromRow, fromCol, toRow, toCol, isEnPassant, isLongCastle, isShortCastle) {
        this.from = [fromRow, fromCol];
        this.to = [toRow, toCol];
        this.is_en_passant = isEnPassant;
        this.is_long_castle = isLongCastle;
        this.is_short_castle = isShortCastle;
    }
}

const games = [
    [
        new Move(1, 4, 3, 4, false, false, false),
        new Move(6, 3, 5, 3, false, false, false),
        new Move(1, 3, 3, 3, false, false, false),
        new Move(7, 6, 5, 5, false, false, false),
        new Move(0, 1, 2, 2, false, false, false),
        new Move(6, 6, 5, 6, false, false, false),
        new Move(0, 2, 2, 4, false, false, false),
        new Move(7, 5, 6, 6, false, false, false),
        new Move(0, 3, 1, 3, false, false, false),
        new Move(6, 2, 5, 2, false, false, false),
        new Move(1, 5, 2, 5, false, false, false),
        new Move(6, 1, 4, 1, false, false, false),
        new Move(0, 6, 1, 4, false, false, false),
        new Move(7, 1, 6, 3, false, false, false),
        new Move(2, 4, 5, 7, false, false, false),
        new Move(6, 6, 5, 7, false, false, false),
        new Move(1, 3, 5, 7, false, false, false),
        new Move(7, 2, 6, 1, false, false, false),
        new Move(1, 0, 2, 0, false, false, false),
        new Move(6, 4, 4, 4, false, false, false),
        new Move(0, 4, 0, 2, false, true, false),
        new Move(7, 3, 6, 4, false, false, false),
        new Move(0, 2, 0, 1, false, false, false),
        new Move(6, 0, 5, 0, false, false, false),
        new Move(1, 4, 0, 2, false, false, false),
        new Move(7, 4, 7, 2, false, true, false),
        new Move(0, 2, 2, 1, false, false, false),
        new Move(4, 4, 3, 3, false, false, false),
        new Move(0, 3, 3, 3, false, false, false),
        new Move(5, 2, 4, 2, false, false, false),
        new Move(3, 3, 0, 3, false, false, false),
        new Move(6, 3, 5, 1, false, false, false),
        new Move(1, 6, 2, 6, false, false, false),
        new Move(7, 2, 7, 1, false, false, false),
        new Move(2, 1, 4, 0, false, false, false),
        new Move(6, 1, 7, 0, false, false, false),
        new Move(0, 5, 2, 7, false, false, false),
        new Move(5, 3, 4, 3, false, false, false),
        new Move(5, 7, 3, 5, false, false, false),
        new Move(7, 1, 6, 0, false, false, false),
        new Move(0, 7, 0, 4, false, false, false),
        new Move(4, 3, 3, 3, false, false, false),
        new Move(2, 2, 4, 3, false, false, false),
        new Move(5, 1, 4, 3, false, false, false),
        new Move(3, 4, 4, 3, false, false, false),
        new Move(6, 4, 5, 3, false, false, false),
        new Move(0, 3, 3, 3, false, false, false),
        new Move(4, 2, 3, 3, false, false, false),
        new Move(0, 4, 6, 4, false, false, false),
        new Move(6, 0, 5, 1, false, false, false),
        new Move(3, 5, 3, 3, false, false, false),
        new Move(5, 1, 4, 0, false, false, false),
        new Move(1, 1, 3, 1, false, false, false),
        new Move(4, 0, 3, 0, false, false, false),
        new Move(3, 3, 2, 2, false, false, false),
        new Move(5, 3, 4, 3, false, false, false),
        new Move(6, 4, 6, 0, false, false, false),
        new Move(7, 0, 6, 1, false, false, false),
        new Move(6, 0, 6, 1, false, false, false),
        new Move(4, 3, 3, 2, false, false, false),
        new Move(2, 2, 5, 5, false, false, false),
        new Move(3, 0, 2, 0, false, false, false),
        new Move(5, 5, 5, 0, false, false, false),
        new Move(2, 0, 3, 1, false, false, false),
        new Move(1, 2, 2, 2, false, false, false),
        new Move(3, 1, 2, 2, false, false, false),
        new Move(5, 0, 0, 0, false, false, false),
        new Move(2, 2, 1, 3, false, false, false),
        new Move(0, 0, 1, 1, false, false, false),
        new Move(1, 3, 0, 3, false, false, false),
        new Move(2, 7, 0, 5, false, false, false),
        new Move(7, 3, 1, 3, false, false, false),
        new Move(6, 1, 6, 3, false, false, false),
        new Move(1, 3, 6, 3, false, false, false),
        new Move(0, 5, 3, 2, false, false, false),
        new Move(4, 1, 3, 2, false, false, false),
        new Move(1, 1, 7, 7, false, false, false),
        new Move(6, 3, 2, 3, false, false, false),
        new Move(7, 7, 7, 0, false, false, false),
        new Move(3, 2, 2, 2, false, false, false),
        new Move(7, 0, 3, 0, false, false, false),
        new Move(0, 3, 0, 4, false, false, false),
        new Move(2, 5, 3, 5, false, false, false),
        new Move(6, 5, 4, 5, false, false, false),
        new Move(0, 1, 0, 2, false, false, false),
        new Move(2, 3, 1, 3, false, false, false),
        new Move(3, 0, 6, 0, false, false, false)
    ]
]